// Mission
export const FETCH_MISSIONS = 'FETCH_MISSIONS';
export const MISSIONS_SUCCESS = 'MISSIONS_SUCCESS';
export const MISSIONS_FAILURE = 'MISSIONS_FAILURE';
export const JOIN_MISSION = 'JOIN_MISSION';
export const LEAVE_MISSION = 'LEAVE_MISSION';
